[backtest]
country = "CN"
portfolio = "CN"
debug_orderbook = false
start_time = "09:30:00"
time_zone = "Asia/Shanghai"
strat_path = "$HOME/automat/hitter/build"
strat_log_path = "$HOME/research/backtest"

[matching_engine]
matching_type = "realistic"     # other choices are: simplistic
feed_latency_us = 0
order_latency_us = 20
fill_latency_us = 30

[tick_data]

    [[tick_data.record]]
    format = "tick"
    exchange = "XHKG"
    path = "$HOME/data/xhkg/"

    [[tick_data.record]]
    format = "tick"
    exchange = "XHKF"
    path = "$HOME/data/xhkg/"

[sql]
backend = "postgres"
server = "aquila"
login = "qijiec"
password = "qijiec"
database = "siriprod"
port = 5432

[log]
file = "backtester"
cout = false
level = "DEBUG"
exclude_tags = []

[[strategy]]
config = "cn_test_1"
universe = [".CSI300"]
partition = ["capi", "sector"]
model = "model_0"
automaton_type = "hitter"
library = "libautomat.so"
sub_portfolio_id = 1
run_period_ms = 100
optim_operiod_ms = 100
log_period_ms = 1000
log_file = "optimizer_1"
misc_symbols = []   # e.g. ["USDCNY", "USDTWD"]
