country = "IN"
debug_orderbook = false
start_time = "09:15:00"
time_zone = "Asia/Kolkata"
strat_path = "$HOME/dev/automat/lib"
log_path = "$HOME/data/backtest"
load_database_positions = 1

[log]
file = "backtester"
cout = false
level = "DEBUG"
exclude_tags = []

[sql]
backend = "postgres"
server = "localhost"
login = "chu"
password = "chu"
database = "siritest"
port = 5432

[tick_data]
    [[tick_data.record]]
    feed_name = "UniFeedBee_XTPL2_ZT_SZT_3"
    format = "parquet"
    exchange = "XSHG"
    utc_offset = 0
    path = "$HOME/data/tick_data/cn/UniFeedBee_XTPL2_ZT_SZT_3/"
    instrument_type = "STOCK"

    [[tick_data.record]]
    feed_name = "UniFeedBee_USTP_ZT_SZT_3"
    format = "parquet"
    exchange = "CFFEX"
    utc_offset = 0
    path = "$HOME/data/tick_data/cn/UniFeedBee_USTP_ZT_SZT_3/"
    instrument_type = "FUTURE"

[matching_engine]
matching_type = "realistic"     # other choices are: simplistic
feed_latency_us = 0
order_latency_us = 20
fill_latency_us = 30

[pnl]
pnl_decomposed = true

    [[pnl.fees]]
    exchange = "XNSE"
    rates = { SSF = [ 1, 1 ], FUTURE = [ 1, 1 ] }

