[backtest]
strategy_type = "hitter"
country = "HK"
portfolio_id = "HK"
debug_orderbook = false
start_time = "09:30:00"
time_zone = "Asia/Hong_Kong"
strat_log_path = "$HOME/research/backtest"

[matching_engine]
matching_type = "realistic"
feed_latency_us = 0
order_latency_us = 20
fill_latency_us = 30

[[raw_data]]
format = "tick"
exchange = "XHKG"
path = "$HOME/data/xhkg/"

[[raw_data]]
format = "tick"
exchange = "XHKF"
path = "$HOME/data/xhkg/"

[sql]
backend = "postgres"
server = "aquila"
login = "qijiec"
password = "qijiec"
database = "siriprod"
port = 5432

[log]
file = "$HOME/logs/sirius/"
level = "DEBUG"
async = false

[[strategy]]
optim_operiod_ms = 100
run_period_ms = 100
log_period_ms = 1000
library = "libautomat.dlib"
universe = "HKALL"
model = "model_0"
sub_portfolio_id = 0
log_file = "optimizer_1"

